name = "MPSTransferMatrix"
uuid = "87d80e04-03a5-42db-b395-4c81662c4174"
authors = ["Wei Tang <tangwei@smail.nju.edu.cn> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
